// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xewryknptzhnfzuctfay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhld3J5a25wdHpobmZ6dWN0ZmF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2OTc4NjgsImV4cCI6MjA2MzI3Mzg2OH0.cMdSnmzfPcojAn38MoKrwmoQs6mI5VrP7H0NlTaafGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);